#!/bin/bash
exec /usr/bin/google-chrome \
  --headless=new \
  --no-sandbox \
  --disable-gpu \
  --disable-dev-shm-usage \
  --autoplay-policy=no-user-gesture-required \
  --disable-features=AudioServiceOutOfProcess \
  --use-fake-ui-for-media-stream \
  --alsa-input-device=pulse \
  --alsa-output-device=pulse \
  --user-data-dir=/tmp/chrome-meeting \
  --remote-debugging-port=18800 \
  "${@:-about:blank}"
